### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by susanlovaglio** [learn-co-curriculum/swift-viewLifeCycle-lab#10]
learn thinks there are tests in the lab. it should just need a pull request instead of running a test for a green light.

**Comment by JimCampagno** [comment]
@AnnJohn Do you think this is something we should be updating ourselves (if so, can you show me :) ) --if not, considering we have two separate tracks, one being this Swift Immersive One and the other being for online stuff--how best can we tackle this problem?

**Comment by AnnJohn** [comment]
@JimCampagno i'm not sure. This looks like something we need to talk to product about; currently we only have the option to make something a lab or a Readme. No option within that to make it test-driven or non-test-driven. I think any lab that shows asking for tests has something to do with a test runner in the repo.
